### ISSUE TITLE
Not an Issue, a question: How to use the Compiler on a page

### ISSUE THREAD

**Issue by amieres** [fsharp/TryFSharp#31]
I would like to use the Fable Compiler to JS from a webpage, just like the REPL does. 
Is there a CDN where the code can be downloaded from and an API that shows how to do this?

**Comment by ReedCopsey** [comment]
@amieres This repository is based on the Fable REPL. I recommend asking there for specifics on how it can be used: https://github.com/fable-compiler/repl
